/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *siwardjebbi_ajout_elec;
  GtkWidget *siwardjebbi_modification_elec;
  GtkWidget *siwardjebbi_supression_elec;
  GtkWidget *siwardjebbi_gestion_elec;
  GtkWidget *sirinebenlakhdhar_ajout;
  GtkWidget *sirinebenlakhdhar_modification;
  GtkWidget *sirinebenlakhdhar_gestion;
  GtkWidget *ahmedmaddouri_ajout;
  GtkWidget *ahmedmaddouri_modification;
  GtkWidget *ahmedmaddouri_gestion;
  GtkWidget *onsmaddouri_ajout;
  GtkWidget *onsmaddouri_gestion;
  GtkWidget *hamzansiri_espace;
  GtkWidget *hamzansiri_ajoutmembre;
  GtkWidget *hamzansiri_modifier_membre;
  GtkWidget *hamzansiri_vote;
  GtkWidget *hamzansiri_listeelectorale;
  GtkWidget *hamzansiri_suppression;
  GtkWidget *onsmaddouri_modifier;
  GtkWidget *authentification_admin;
  GtkWidget *authentification_utilisateur;
  GtkWidget *authentification_observateur;
  GtkWidget *authentification_agenbv;
  GtkWidget *choix_auth;
  GtkWidget *Admin;
  GtkWidget *Electeur;
  GtkWidget *Observateur;
  GtkWidget *AgentBV;
  GtkWidget *fares_frini_Affichage;
  GtkWidget *fares_frini_ajouter;
  GtkWidget *fares_frini_modifier;
  GtkWidget *fares_frini_confirmer_supp;
  GtkWidget *fares_frini_confirmer_modifier;
  GtkWidget *fares_frini_resultat_ajout_echec;
  GtkWidget *fares_frini_resultat_modif_succ;
  GtkWidget *fares_frini_resultat_modif_echec;
  GtkWidget *fares_frini_resultat_supp_succ;
  GtkWidget *fares_frini_resultat_supp_echec;
  GtkWidget *fares_frini_modif_nom;
  GtkWidget *fares_frini_modif_prenom;
  GtkWidget *fares_frini_modif_age;
  GtkWidget *fares_frini_modif_sexe;
  GtkWidget *fares_frini_modif_etat;
  GtkWidget *fares_frini_confirmer_ajout;
  GtkWidget *fares_frini_ajout_succ;
  GtkWidget *fares_frini_statistique;
  GtkWidget *fares_frini_recherche_afficher;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*siwardjebbi_ajout_elec = create_siwardjebbi_ajout_elec ();
  gtk_widget_show (siwardjebbi_ajout_elec);
  siwardjebbi_modification_elec = create_siwardjebbi_modification_elec ();
  gtk_widget_show (siwardjebbi_modification_elec);
  siwardjebbi_supression_elec = create_siwardjebbi_supression_elec ();
  gtk_widget_show (siwardjebbi_supression_elec);
  siwardjebbi_gestion_elec = create_siwardjebbi_gestion_elec ();
  gtk_widget_show (siwardjebbi_gestion_elec);
  sirinebenlakhdhar_ajout = create_sirinebenlakhdhar_ajout ();
  gtk_widget_show (sirinebenlakhdhar_ajout);
  sirinebenlakhdhar_modification = create_sirinebenlakhdhar_modification ();
  gtk_widget_show (sirinebenlakhdhar_modification);
  sirinebenlakhdhar_gestion = create_sirinebenlakhdhar_gestion ();
  gtk_widget_show (sirinebenlakhdhar_gestion);
  ahmedmaddouri_ajout = create_ahmedmaddouri_ajout ();
  gtk_widget_show (ahmedmaddouri_ajout);
  ahmedmaddouri_modification = create_ahmedmaddouri_modification ();
  gtk_widget_show (ahmedmaddouri_modification);
  ahmedmaddouri_gestion = create_ahmedmaddouri_gestion ();
  gtk_widget_show (ahmedmaddouri_gestion);
  onsmaddouri_ajout = create_onsmaddouri_ajout ();
  gtk_widget_show (onsmaddouri_ajout);
  onsmaddouri_gestion = create_onsmaddouri_gestion ();
  gtk_widget_show (onsmaddouri_gestion);
  hamzansiri_espace = create_hamzansiri_espace ();
  gtk_widget_show (hamzansiri_espace);
  hamzansiri_ajoutmembre = create_hamzansiri_ajoutmembre ();
  gtk_widget_show (hamzansiri_ajoutmembre);
  hamzansiri_modifier_membre = create_hamzansiri_modifier_membre ();
  gtk_widget_show (hamzansiri_modifier_membre);
  hamzansiri_vote = create_hamzansiri_vote ();
  gtk_widget_show (hamzansiri_vote);
  hamzansiri_listeelectorale = create_hamzansiri_listeelectorale ();
  gtk_widget_show (hamzansiri_listeelectorale);
  hamzansiri_suppression = create_hamzansiri_suppression ();
  gtk_widget_show (hamzansiri_suppression);
  onsmaddouri_modifier = create_onsmaddouri_modifier ();
  gtk_widget_show (onsmaddouri_modifier);
  authentification_admin = create_authentification_admin ();
  gtk_widget_show (authentification_admin);*/
  authentification_utilisateur = create_authentification_utilisateur ();
  gtk_widget_show (authentification_utilisateur);
  /*authentification_observateur = create_authentification_observateur ();
  gtk_widget_show (authentification_observateur);
  authentification_agenbv = create_authentification_agenbv ();
  gtk_widget_show (authentification_agenbv);
  choix_auth = create_choix_auth ();
  gtk_widget_show (choix_auth);
  Admin = create_Admin ();
  gtk_widget_show (Admin);
  Electeur = create_Electeur ();
  gtk_widget_show (Electeur);
  Observateur = create_Observateur ();
  gtk_widget_show (Observateur);
  AgentBV = create_AgentBV ();
  gtk_widget_show (AgentBV);
  fares_frini_Affichage = create_fares_frini_Affichage ();
  gtk_widget_show (fares_frini_Affichage);
  fares_frini_ajouter = create_fares_frini_ajouter ();
  gtk_widget_show (fares_frini_ajouter);
  fares_frini_modifier = create_fares_frini_modifier ();
  gtk_widget_show (fares_frini_modifier);
  fares_frini_confirmer_supp = create_fares_frini_confirmer_supp ();
  gtk_widget_show (fares_frini_confirmer_supp);
  fares_frini_confirmer_modifier = create_fares_frini_confirmer_modifier ();
  gtk_widget_show (fares_frini_confirmer_modifier);
  fares_frini_resultat_ajout_echec = create_fares_frini_resultat_ajout_echec ();
  gtk_widget_show (fares_frini_resultat_ajout_echec);
  fares_frini_resultat_modif_succ = create_fares_frini_resultat_modif_succ ();
  gtk_widget_show (fares_frini_resultat_modif_succ);
  fares_frini_resultat_modif_echec = create_fares_frini_resultat_modif_echec ();
  gtk_widget_show (fares_frini_resultat_modif_echec);
  fares_frini_resultat_supp_succ = create_fares_frini_resultat_supp_succ ();
  gtk_widget_show (fares_frini_resultat_supp_succ);
  fares_frini_resultat_supp_echec = create_fares_frini_resultat_supp_echec ();
  gtk_widget_show (fares_frini_resultat_supp_echec);
  fares_frini_modif_nom = create_fares_frini_modif_nom ();
  gtk_widget_show (fares_frini_modif_nom);
  fares_frini_modif_prenom = create_fares_frini_modif_prenom ();
  gtk_widget_show (fares_frini_modif_prenom);
  fares_frini_modif_age = create_fares_frini_modif_age ();
  gtk_widget_show (fares_frini_modif_age);
  fares_frini_modif_sexe = create_fares_frini_modif_sexe ();
  gtk_widget_show (fares_frini_modif_sexe);
  fares_frini_modif_etat = create_fares_frini_modif_etat ();
  gtk_widget_show (fares_frini_modif_etat);
  fares_frini_confirmer_ajout = create_fares_frini_confirmer_ajout ();
  gtk_widget_show (fares_frini_confirmer_ajout);
  fares_frini_ajout_succ = create_fares_frini_ajout_succ ();
  gtk_widget_show (fares_frini_ajout_succ);
  fares_frini_statistique = create_fares_frini_statistique ();
  gtk_widget_show (fares_frini_statistique);
  fares_frini_recherche_afficher = create_fares_frini_recherche_afficher ();
  gtk_widget_show (fares_frini_recherche_afficher);*/

  gtk_main ();
  return 0;
}

