/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Affichage (void);
GtkWidget* create_authentification (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_confirmer_ajout (void);
GtkWidget* create_resultat_ajout_succ (void);
GtkWidget* create_modifier (void);
GtkWidget* create_confirmer_supp (void);
GtkWidget* create_confirmer_modifier (void);
GtkWidget* create_resultat_ajout_echec (void);
GtkWidget* create_resultat_modif_succ (void);
GtkWidget* create_resultat_modif_echec (void);
GtkWidget* create_resultat_supp_succ (void);
GtkWidget* create_resultat_supp_echec (void);
GtkWidget* create_auth_echec (void);
GtkWidget* create_modif_nom (void);
GtkWidget* create_modif_prenom (void);
GtkWidget* create_modif_age (void);
GtkWidget* create_modif_sexe (void);
GtkWidget* create_modif_etat (void);
