/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Affichage (void)
{
  GtkWidget *Affichage;
  GtkWidget *fixed1;
  GtkWidget *recherche_entry;
  GtkWidget *ajout_button;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *modifier_button;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *supprimer_button;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label10;
  GtkWidget *raffraichir_button;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label11;
  GtkWidget *recherche_button;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label14;
  GtkWidget *recherche_label;
  GtkWidget *bv_combobox;
  GtkWidget *scrolledwindow;
  GtkWidget *treeview;
  GtkWidget *deconexion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *id_admin;
  GtkWidget *label_admin;
  GtkWidget *image_admin;
  GtkWidget *image25;
  GtkWidget *image26;
  GtkWidget *gestion_utilisateur_label;
  GtkWidget *image28;
  GtkWidget *image29;
  GtkWidget *image30;
  GtkWidget *image31;
  GtkWidget *image27;
  GtkWidget *resultat_label;
  GtkWidget *image32;
  GtkWidget *label_bv;
  GtkWidget *appliquer_bv_button;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *resultat_bv;
  GtkWidget *verifier;
  GtkWidget *image33;

  Affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Affichage, 1300, 710);
  gtk_window_set_title (GTK_WINDOW (Affichage), _("Gestion Utilisateur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Affichage), fixed1);

  recherche_entry = gtk_entry_new ();
  gtk_widget_show (recherche_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche_entry, 816, 200);
  gtk_widget_set_size_request (recherche_entry, 176, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (recherche_entry), 8226);

  ajout_button = gtk_button_new ();
  gtk_widget_show (ajout_button);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_button, 64, 80);
  gtk_widget_set_size_request (ajout_button, 120, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ajout_button), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("AJOUTER"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  modifier_button = gtk_button_new ();
  gtk_widget_show (modifier_button);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier_button, 208, 80);
  gtk_widget_set_size_request (modifier_button, 120, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (modifier_button), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("MODIFER"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  supprimer_button = gtk_button_new ();
  gtk_widget_show (supprimer_button);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer_button, 352, 80);
  gtk_widget_set_size_request (supprimer_button, 120, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprimer_button), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  raffraichir_button = gtk_button_new ();
  gtk_widget_show (raffraichir_button);
  gtk_fixed_put (GTK_FIXED (fixed1), raffraichir_button, 648, 80);
  gtk_widget_set_size_request (raffraichir_button, 120, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (raffraichir_button), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Raffraichir"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  recherche_button = gtk_button_new ();
  gtk_widget_show (recherche_button);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche_button, 992, 200);
  gtk_widget_set_size_request (recherche_button, 120, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (recherche_button), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox7), label14, FALSE, FALSE, 0);

  recherche_label = gtk_label_new (_("Recherche d'un utilisateur selon l'ID"));
  gtk_widget_show (recherche_label);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche_label, 880, 96);
  gtk_widget_set_size_request (recherche_label, 272, 56);

  bv_combobox = gtk_combo_box_new_text ();
  gtk_widget_show (bv_combobox);
  gtk_fixed_put (GTK_FIXED (fixed1), bv_combobox, 876, 372);
  gtk_widget_set_size_request (bv_combobox, 144, 48);

  scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow, 0, 136);
  gtk_widget_set_size_request (scrolledwindow, 784, 568);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow), treeview);
  gtk_widget_set_size_request (treeview, 720, 544);

  deconexion = gtk_button_new ();
  gtk_widget_show (deconexion);
  gtk_fixed_put (GTK_FIXED (fixed1), deconexion, 1064, 664);
  gtk_widget_set_size_request (deconexion, 128, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (deconexion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("D\303\251connexion"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  id_admin = gtk_label_new (_("ID: "));
  gtk_widget_show (id_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), id_admin, 1040, 592);
  gtk_widget_set_size_request (id_admin, 152, 32);

  label_admin = gtk_label_new (_("ADMIN"));
  gtk_widget_show (label_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), label_admin, 1040, 536);
  gtk_widget_set_size_request (label_admin, 160, 32);

  image_admin = create_pixmap (Affichage, "download.jpeg");
  gtk_widget_show (image_admin);
  gtk_fixed_put (GTK_FIXED (fixed1), image_admin, 904, 528);
  gtk_widget_set_size_request (image_admin, 136, 181);

  image25 = create_pixmap (Affichage, "black_Color.jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed1), image25, 880, 524);
  gtk_widget_set_size_request (image25, 424, 5);

  image26 = create_pixmap (Affichage, "black_Color.jpg");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed1), image26, 876, 524);
  gtk_widget_set_size_request (image26, 5, 195);

  gestion_utilisateur_label = gtk_label_new (_("Gestion Utilisateur"));
  gtk_widget_show (gestion_utilisateur_label);
  gtk_fixed_put (GTK_FIXED (fixed1), gestion_utilisateur_label, 544, 8);
  gtk_widget_set_size_request (gestion_utilisateur_label, 208, 40);
  gtk_misc_set_alignment (GTK_MISC (gestion_utilisateur_label), 0.5, 0.47);

  image28 = create_pixmap (Affichage, "red.jpeg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed1), image28, 144, 0);
  gtk_widget_set_size_request (image28, 312, 62);

  image29 = create_pixmap (Affichage, "red.jpeg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed1), image29, 0, 0);
  gtk_widget_set_size_request (image29, 312, 62);

  image30 = create_pixmap (Affichage, "red.jpeg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed1), image30, 752, 0);
  gtk_widget_set_size_request (image30, 312, 62);

  image31 = create_pixmap (Affichage, "red.jpeg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed1), image31, 1048, 0);
  gtk_widget_set_size_request (image31, 312, 62);

  image27 = create_pixmap (Affichage, "red.jpeg");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed1), image27, 448, 0);
  gtk_widget_set_size_request (image27, 312, 62);

  resultat_label = gtk_label_new (_("R\303\251sultat de la Recherche"));
  gtk_widget_show (resultat_label);
  gtk_fixed_put (GTK_FIXED (fixed1), resultat_label, 792, 240);
  gtk_widget_set_size_request (resultat_label, 352, 64);

  image32 = create_pixmap (Affichage, "black_Color.jpg");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed1), image32, 784, 305);
  gtk_widget_set_size_request (image32, 515, 5);

  label_bv = gtk_label_new (_("Assignement Aux Bureaux De Votes"));
  gtk_widget_show (label_bv);
  gtk_fixed_put (GTK_FIXED (fixed1), label_bv, 896, 304);
  gtk_widget_set_size_request (label_bv, 272, 56);

  appliquer_bv_button = gtk_button_new ();
  gtk_widget_show (appliquer_bv_button);
  gtk_fixed_put (GTK_FIXED (fixed1), appliquer_bv_button, 896, 456);
  gtk_widget_set_size_request (appliquer_bv_button, 144, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (appliquer_bv_button), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Appliquer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  resultat_bv = gtk_label_new ("");
  gtk_widget_show (resultat_bv);
  gtk_fixed_put (GTK_FIXED (fixed1), resultat_bv, 1040, 456);
  gtk_widget_set_size_request (resultat_bv, 248, 48);

  verifier = gtk_button_new ();
  gtk_widget_show (verifier);
  gtk_fixed_put (GTK_FIXED (fixed1), verifier, 1016, 372);
  gtk_widget_set_size_request (verifier, 48, 48);

  image33 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_container_add (GTK_CONTAINER (verifier), image33);

  g_signal_connect ((gpointer) ajout_button, "clicked",
                    G_CALLBACK (on_ajout_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_button, "clicked",
                    G_CALLBACK (on_modifier_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_button, "clicked",
                    G_CALLBACK (on_supprimer_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) raffraichir_button, "clicked",
                    G_CALLBACK (on_raffraichir_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_button, "clicked",
                    G_CALLBACK (on_recherche_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) deconexion, "clicked",
                    G_CALLBACK (on_deconexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) appliquer_bv_button, "clicked",
                    G_CALLBACK (on_appliquer_bv_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) verifier, "clicked",
                    G_CALLBACK (on_verifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Affichage, Affichage, "Affichage");
  GLADE_HOOKUP_OBJECT (Affichage, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Affichage, recherche_entry, "recherche_entry");
  GLADE_HOOKUP_OBJECT (Affichage, ajout_button, "ajout_button");
  GLADE_HOOKUP_OBJECT (Affichage, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Affichage, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Affichage, image4, "image4");
  GLADE_HOOKUP_OBJECT (Affichage, label8, "label8");
  GLADE_HOOKUP_OBJECT (Affichage, modifier_button, "modifier_button");
  GLADE_HOOKUP_OBJECT (Affichage, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Affichage, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Affichage, image5, "image5");
  GLADE_HOOKUP_OBJECT (Affichage, label9, "label9");
  GLADE_HOOKUP_OBJECT (Affichage, supprimer_button, "supprimer_button");
  GLADE_HOOKUP_OBJECT (Affichage, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Affichage, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Affichage, image6, "image6");
  GLADE_HOOKUP_OBJECT (Affichage, label10, "label10");
  GLADE_HOOKUP_OBJECT (Affichage, raffraichir_button, "raffraichir_button");
  GLADE_HOOKUP_OBJECT (Affichage, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Affichage, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Affichage, image7, "image7");
  GLADE_HOOKUP_OBJECT (Affichage, label11, "label11");
  GLADE_HOOKUP_OBJECT (Affichage, recherche_button, "recherche_button");
  GLADE_HOOKUP_OBJECT (Affichage, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Affichage, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Affichage, image8, "image8");
  GLADE_HOOKUP_OBJECT (Affichage, label14, "label14");
  GLADE_HOOKUP_OBJECT (Affichage, recherche_label, "recherche_label");
  GLADE_HOOKUP_OBJECT (Affichage, bv_combobox, "bv_combobox");
  GLADE_HOOKUP_OBJECT (Affichage, scrolledwindow, "scrolledwindow");
  GLADE_HOOKUP_OBJECT (Affichage, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (Affichage, deconexion, "deconexion");
  GLADE_HOOKUP_OBJECT (Affichage, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Affichage, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Affichage, image2, "image2");
  GLADE_HOOKUP_OBJECT (Affichage, label4, "label4");
  GLADE_HOOKUP_OBJECT (Affichage, id_admin, "id_admin");
  GLADE_HOOKUP_OBJECT (Affichage, label_admin, "label_admin");
  GLADE_HOOKUP_OBJECT (Affichage, image_admin, "image_admin");
  GLADE_HOOKUP_OBJECT (Affichage, image25, "image25");
  GLADE_HOOKUP_OBJECT (Affichage, image26, "image26");
  GLADE_HOOKUP_OBJECT (Affichage, gestion_utilisateur_label, "gestion_utilisateur_label");
  GLADE_HOOKUP_OBJECT (Affichage, image28, "image28");
  GLADE_HOOKUP_OBJECT (Affichage, image29, "image29");
  GLADE_HOOKUP_OBJECT (Affichage, image30, "image30");
  GLADE_HOOKUP_OBJECT (Affichage, image31, "image31");
  GLADE_HOOKUP_OBJECT (Affichage, image27, "image27");
  GLADE_HOOKUP_OBJECT (Affichage, resultat_label, "resultat_label");
  GLADE_HOOKUP_OBJECT (Affichage, image32, "image32");
  GLADE_HOOKUP_OBJECT (Affichage, label_bv, "label_bv");
  GLADE_HOOKUP_OBJECT (Affichage, appliquer_bv_button, "appliquer_bv_button");
  GLADE_HOOKUP_OBJECT (Affichage, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Affichage, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Affichage, image3, "image3");
  GLADE_HOOKUP_OBJECT (Affichage, label5, "label5");
  GLADE_HOOKUP_OBJECT (Affichage, resultat_bv, "resultat_bv");
  GLADE_HOOKUP_OBJECT (Affichage, verifier, "verifier");
  GLADE_HOOKUP_OBJECT (Affichage, image33, "image33");

  return Affichage;
}

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed2;
  GtkWidget *auth_id_entry;
  GtkWidget *auth_mdp_entry;
  GtkWidget *auth_login_entry;
  GtkWidget *id_admin_auth_label;
  GtkWidget *admin_log_auth_label;
  GtkWidget *admin_mdp_auth_label;
  GtkWidget *valid_auth_admin;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label16;
  GtkWidget *admin_auth_titre_label;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification, 380, 315);
  gtk_window_set_title (GTK_WINDOW (authentification), _("Authentification"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (authentification), fixed2);

  auth_id_entry = gtk_entry_new ();
  gtk_widget_show (auth_id_entry);
  gtk_fixed_put (GTK_FIXED (fixed2), auth_id_entry, 160, 80);
  gtk_widget_set_size_request (auth_id_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (auth_id_entry), 8226);

  auth_mdp_entry = gtk_entry_new ();
  gtk_widget_show (auth_mdp_entry);
  gtk_fixed_put (GTK_FIXED (fixed2), auth_mdp_entry, 160, 170);
  gtk_widget_set_size_request (auth_mdp_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (auth_mdp_entry), 8226);

  auth_login_entry = gtk_entry_new ();
  gtk_widget_show (auth_login_entry);
  gtk_fixed_put (GTK_FIXED (fixed2), auth_login_entry, 160, 125);
  gtk_widget_set_size_request (auth_login_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (auth_login_entry), 8226);

  id_admin_auth_label = gtk_label_new (_("ID"));
  gtk_widget_show (id_admin_auth_label);
  gtk_fixed_put (GTK_FIXED (fixed2), id_admin_auth_label, 56, 80);
  gtk_widget_set_size_request (id_admin_auth_label, 88, 24);

  admin_log_auth_label = gtk_label_new (_("Login"));
  gtk_widget_show (admin_log_auth_label);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_log_auth_label, 64, 128);
  gtk_widget_set_size_request (admin_log_auth_label, 64, 24);

  admin_mdp_auth_label = gtk_label_new (_("Mot de Passe"));
  gtk_widget_show (admin_mdp_auth_label);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_mdp_auth_label, 32, 172);
  gtk_widget_set_size_request (admin_mdp_auth_label, 128, 25);

  valid_auth_admin = gtk_button_new ();
  gtk_widget_show (valid_auth_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), valid_auth_admin, 120, 256);
  gtk_widget_set_size_request (valid_auth_admin, 152, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (valid_auth_admin), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Authentification"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  admin_auth_titre_label = gtk_label_new (_("Authentification Admin"));
  gtk_widget_show (admin_auth_titre_label);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_auth_titre_label, 104, 0);
  gtk_widget_set_size_request (admin_auth_titre_label, 192, 40);

  g_signal_connect ((gpointer) valid_auth_admin, "clicked",
                    G_CALLBACK (on_valid_auth_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (authentification, auth_id_entry, "auth_id_entry");
  GLADE_HOOKUP_OBJECT (authentification, auth_mdp_entry, "auth_mdp_entry");
  GLADE_HOOKUP_OBJECT (authentification, auth_login_entry, "auth_login_entry");
  GLADE_HOOKUP_OBJECT (authentification, id_admin_auth_label, "id_admin_auth_label");
  GLADE_HOOKUP_OBJECT (authentification, admin_log_auth_label, "admin_log_auth_label");
  GLADE_HOOKUP_OBJECT (authentification, admin_mdp_auth_label, "admin_mdp_auth_label");
  GLADE_HOOKUP_OBJECT (authentification, valid_auth_admin, "valid_auth_admin");
  GLADE_HOOKUP_OBJECT (authentification, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (authentification, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (authentification, image9, "image9");
  GLADE_HOOKUP_OBJECT (authentification, label16, "label16");
  GLADE_HOOKUP_OBJECT (authentification, admin_auth_titre_label, "admin_auth_titre_label");

  return authentification;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed3;
  GtkWidget *ajouter_nom_entry;
  GtkWidget *ajouter_cin_entry;
  GtkWidget *ajouter_prenom_entry;
  GtkObject *jour_spin_adj;
  GtkWidget *jour_spin;
  GtkObject *mois_spin_adj;
  GtkWidget *mois_spin;
  GtkObject *annee_spin_adj;
  GtkWidget *annee_spin;
  GtkWidget *ajouter_titre_label;
  GtkWidget *ajouter_role_label;
  GtkWidget *ajouter_nom_label;
  GtkWidget *ajouter_prenom_label;
  GtkWidget *ajouter_cin_label;
  GtkWidget *ajouter_sexe_label;
  GtkWidget *ajouter_anne_label;
  GtkWidget *ajouter_mois_label;
  GtkWidget *ajouter_jour_label;
  GtkWidget *ajouter_datenaissance_label;
  GtkWidget *ajouter_button;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label30;
  GtkWidget *ajouter_homme_radiobutton;
  GSList *ajouter_homme_radiobutton_group = NULL;
  GtkWidget *ajouter_erreur_label;
  GtkWidget *ajouter_femme_radiobutton;
  GtkWidget *ajouter_role_electeur_radiobutton;
  GSList *ajouter_role_electeur_radiobutton_group = NULL;
  GtkWidget *ajouter_role_agentbv_radiobutton;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajouter, 450, 487);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("Ajouter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed3);

  ajouter_nom_entry = gtk_entry_new ();
  gtk_widget_show (ajouter_nom_entry);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_nom_entry, 48, 96);
  gtk_widget_set_size_request (ajouter_nom_entry, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajouter_nom_entry), 8226);

  ajouter_cin_entry = gtk_entry_new ();
  gtk_widget_show (ajouter_cin_entry);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_cin_entry, 48, 160);
  gtk_widget_set_size_request (ajouter_cin_entry, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajouter_cin_entry), 8226);

  ajouter_prenom_entry = gtk_entry_new ();
  gtk_widget_show (ajouter_prenom_entry);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_prenom_entry, 240, 96);
  gtk_widget_set_size_request (ajouter_prenom_entry, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajouter_prenom_entry), 8226);

  jour_spin_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_spin = gtk_spin_button_new (GTK_ADJUSTMENT (jour_spin_adj), 1, 0);
  gtk_widget_show (jour_spin);
  gtk_fixed_put (GTK_FIXED (fixed3), jour_spin, 48, 264);
  gtk_widget_set_size_request (jour_spin, 64, 32);

  mois_spin_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_spin = gtk_spin_button_new (GTK_ADJUSTMENT (mois_spin_adj), 1, 0);
  gtk_widget_show (mois_spin);
  gtk_fixed_put (GTK_FIXED (fixed3), mois_spin, 168, 264);
  gtk_widget_set_size_request (mois_spin, 64, 32);

  annee_spin_adj = gtk_adjustment_new (2022, 1920, 2022, 1, 10, 10);
  annee_spin = gtk_spin_button_new (GTK_ADJUSTMENT (annee_spin_adj), 1, 0);
  gtk_widget_show (annee_spin);
  gtk_fixed_put (GTK_FIXED (fixed3), annee_spin, 288, 264);
  gtk_widget_set_size_request (annee_spin, 64, 32);

  ajouter_titre_label = gtk_label_new (_("Ajouter un utilisateur"));
  gtk_widget_show (ajouter_titre_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_titre_label, 144, 16);
  gtk_widget_set_size_request (ajouter_titre_label, 176, 40);

  ajouter_role_label = gtk_label_new (_("Role:"));
  gtk_widget_show (ajouter_role_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_role_label, 176, 304);
  gtk_widget_set_size_request (ajouter_role_label, 80, 24);

  ajouter_nom_label = gtk_label_new (_("Nom"));
  gtk_widget_show (ajouter_nom_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_nom_label, 48, 72);
  gtk_widget_set_size_request (ajouter_nom_label, 49, 17);

  ajouter_prenom_label = gtk_label_new (_("Prenom"));
  gtk_widget_show (ajouter_prenom_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_prenom_label, 240, 72);
  gtk_widget_set_size_request (ajouter_prenom_label, 56, 16);

  ajouter_cin_label = gtk_label_new (_("CIN"));
  gtk_widget_show (ajouter_cin_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_cin_label, 48, 136);
  gtk_widget_set_size_request (ajouter_cin_label, 49, 17);

  ajouter_sexe_label = gtk_label_new (_("Sexe"));
  gtk_widget_show (ajouter_sexe_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_sexe_label, 240, 136);
  gtk_widget_set_size_request (ajouter_sexe_label, 49, 17);

  ajouter_anne_label = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (ajouter_anne_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_anne_label, 288, 240);
  gtk_widget_set_size_request (ajouter_anne_label, 56, 16);

  ajouter_mois_label = gtk_label_new (_("Mois"));
  gtk_widget_show (ajouter_mois_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_mois_label, 168, 240);
  gtk_widget_set_size_request (ajouter_mois_label, 49, 17);

  ajouter_jour_label = gtk_label_new (_("Jour"));
  gtk_widget_show (ajouter_jour_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_jour_label, 32, 240);
  gtk_widget_set_size_request (ajouter_jour_label, 64, 16);

  ajouter_datenaissance_label = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (ajouter_datenaissance_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_datenaissance_label, 24, 208);
  gtk_widget_set_size_request (ajouter_datenaissance_label, 168, 32);

  ajouter_button = gtk_button_new ();
  gtk_widget_show (ajouter_button);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_button, 160, 432);
  gtk_widget_set_size_request (ajouter_button, 120, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ajouter_button), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox9), label30, FALSE, FALSE, 0);

  ajouter_homme_radiobutton = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (ajouter_homme_radiobutton);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_homme_radiobutton, 240, 160);
  gtk_widget_set_size_request (ajouter_homme_radiobutton, 80, 31);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajouter_homme_radiobutton), ajouter_homme_radiobutton_group);
  ajouter_homme_radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajouter_homme_radiobutton));

  ajouter_erreur_label = gtk_label_new ("");
  gtk_widget_show (ajouter_erreur_label);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_erreur_label, 32, 368);
  gtk_widget_set_size_request (ajouter_erreur_label, 368, 64);

  ajouter_femme_radiobutton = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (ajouter_femme_radiobutton);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_femme_radiobutton, 324, 160);
  gtk_widget_set_size_request (ajouter_femme_radiobutton, 80, 31);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajouter_femme_radiobutton), ajouter_homme_radiobutton_group);
  ajouter_homme_radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajouter_femme_radiobutton));

  ajouter_role_electeur_radiobutton = gtk_radio_button_new_with_mnemonic (NULL, _("Electeur"));
  gtk_widget_show (ajouter_role_electeur_radiobutton);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_role_electeur_radiobutton, 80, 344);
  gtk_widget_set_size_request (ajouter_role_electeur_radiobutton, 128, 32);
  gtk_container_set_border_width (GTK_CONTAINER (ajouter_role_electeur_radiobutton), 9);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajouter_role_electeur_radiobutton), ajouter_role_electeur_radiobutton_group);
  ajouter_role_electeur_radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajouter_role_electeur_radiobutton));

  ajouter_role_agentbv_radiobutton = gtk_radio_button_new_with_mnemonic (NULL, _("Agent de Bureau de Vote"));
  gtk_widget_show (ajouter_role_agentbv_radiobutton);
  gtk_fixed_put (GTK_FIXED (fixed3), ajouter_role_agentbv_radiobutton, 232, 344);
  gtk_widget_set_size_request (ajouter_role_agentbv_radiobutton, 160, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajouter_role_agentbv_radiobutton), ajouter_role_electeur_radiobutton_group);
  ajouter_role_electeur_radiobutton_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajouter_role_agentbv_radiobutton));

  g_signal_connect ((gpointer) ajouter_button, "clicked",
                    G_CALLBACK (on_ajouter_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_homme_radiobutton, "toggled",
                    G_CALLBACK (on_ajouter_homme_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajouter_femme_radiobutton, "toggled",
                    G_CALLBACK (on_ajouter_femme_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajouter_role_electeur_radiobutton, "toggled",
                    G_CALLBACK (on_ajouter_role_electeur_radiobutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajouter_role_agentbv_radiobutton, "toggled",
                    G_CALLBACK (on_ajouter_role_agentbv_radiobutton_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_nom_entry, "ajouter_nom_entry");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_cin_entry, "ajouter_cin_entry");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_prenom_entry, "ajouter_prenom_entry");
  GLADE_HOOKUP_OBJECT (ajouter, jour_spin, "jour_spin");
  GLADE_HOOKUP_OBJECT (ajouter, mois_spin, "mois_spin");
  GLADE_HOOKUP_OBJECT (ajouter, annee_spin, "annee_spin");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_titre_label, "ajouter_titre_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_role_label, "ajouter_role_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_nom_label, "ajouter_nom_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_prenom_label, "ajouter_prenom_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_cin_label, "ajouter_cin_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_sexe_label, "ajouter_sexe_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_anne_label, "ajouter_anne_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_mois_label, "ajouter_mois_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_jour_label, "ajouter_jour_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_datenaissance_label, "ajouter_datenaissance_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_button, "ajouter_button");
  GLADE_HOOKUP_OBJECT (ajouter, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajouter, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajouter, image10, "image10");
  GLADE_HOOKUP_OBJECT (ajouter, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_homme_radiobutton, "ajouter_homme_radiobutton");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_erreur_label, "ajouter_erreur_label");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_femme_radiobutton, "ajouter_femme_radiobutton");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_role_electeur_radiobutton, "ajouter_role_electeur_radiobutton");
  GLADE_HOOKUP_OBJECT (ajouter, ajouter_role_agentbv_radiobutton, "ajouter_role_agentbv_radiobutton");

  return ajouter;
}

GtkWidget*
create_confirmer_ajout (void)
{
  GtkWidget *confirmer_ajout;
  GtkWidget *fixed4;
  GtkWidget *confirmer_annuler_button;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label34;
  GtkWidget *confirmer_titre_label;
  GtkWidget *ajouter_confirmer_label;
  GtkWidget *confirmer_button;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label35;

  confirmer_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (confirmer_ajout, 340, 245);
  gtk_window_set_title (GTK_WINDOW (confirmer_ajout), _("Confirmer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (confirmer_ajout), fixed4);

  confirmer_annuler_button = gtk_button_new ();
  gtk_widget_show (confirmer_annuler_button);
  gtk_fixed_put (GTK_FIXED (fixed4), confirmer_annuler_button, 32, 176);
  gtk_widget_set_size_request (confirmer_annuler_button, 120, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (confirmer_annuler_button), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox10), label34, FALSE, FALSE, 0);

  confirmer_titre_label = gtk_label_new (_("Voulez vous Vraiment Ajouter \nCet Utilisateur"));
  gtk_widget_show (confirmer_titre_label);
  gtk_fixed_put (GTK_FIXED (fixed4), confirmer_titre_label, 16, 80);
  gtk_widget_set_size_request (confirmer_titre_label, 304, 40);
  gtk_label_set_justify (GTK_LABEL (confirmer_titre_label), GTK_JUSTIFY_CENTER);

  ajouter_confirmer_label = gtk_label_new ("");
  gtk_widget_show (ajouter_confirmer_label);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter_confirmer_label, 0, 48);
  gtk_widget_set_size_request (ajouter_confirmer_label, 328, 120);

  confirmer_button = gtk_button_new ();
  gtk_widget_show (confirmer_button);
  gtk_fixed_put (GTK_FIXED (fixed4), confirmer_button, 176, 176);
  gtk_widget_set_size_request (confirmer_button, 120, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (confirmer_button), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox11), label35, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) confirmer_annuler_button, "clicked",
                    G_CALLBACK (on_confirmer_annuler_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer_button, "clicked",
                    G_CALLBACK (on_confirmer_ajout_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmer_ajout, confirmer_ajout, "confirmer_ajout");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, confirmer_annuler_button, "confirmer_annuler_button");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, image11, "image11");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, label34, "label34");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, confirmer_titre_label, "confirmer_titre_label");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, ajouter_confirmer_label, "ajouter_confirmer_label");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, confirmer_button, "confirmer_button");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, image12, "image12");
  GLADE_HOOKUP_OBJECT (confirmer_ajout, label35, "label35");

  return confirmer_ajout;
}

GtkWidget*
create_resultat_ajout_succ (void)
{
  GtkWidget *resultat_ajout_succ;
  GtkWidget *fixed5;
  GtkWidget *continuer_button;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label37;
  GtkWidget *resultat_label;

  resultat_ajout_succ = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (resultat_ajout_succ), fixed5);

  continuer_button = gtk_button_new ();
  gtk_widget_show (continuer_button);
  gtk_fixed_put (GTK_FIXED (fixed5), continuer_button, 128, 152);
  gtk_widget_set_size_request (continuer_button, 136, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (continuer_button), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox12), label37, FALSE, FALSE, 0);

  resultat_label = gtk_label_new (_("L'utilisateur a \303\251t\303\251 ajout\303\251 avec Succ\303\251s"));
  gtk_widget_show (resultat_label);
  gtk_fixed_put (GTK_FIXED (fixed5), resultat_label, 24, 16);
  gtk_widget_set_size_request (resultat_label, 352, 88);

  g_signal_connect ((gpointer) continuer_button, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (resultat_ajout_succ, resultat_ajout_succ, "resultat_ajout_succ");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, continuer_button, "continuer_button");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, image13, "image13");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, label37, "label37");
  GLADE_HOOKUP_OBJECT (resultat_ajout_succ, resultat_label, "resultat_label");

  return resultat_ajout_succ;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed6;
  GtkWidget *modifier_titre_label;
  GtkWidget *image35;
  GtkWidget *modifier_modifier_button;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label41;
  GtkWidget *image34;
  GtkWidget *modif_date_checkbox;
  GtkWidget *modif_sexe_checkbox;
  GtkWidget *modif_nom_check;
  GtkWidget *modif_Prenom_checkbox;
  GtkWidget *modif_etat_checkbox;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier, 380, 330);
  gtk_window_set_title (GTK_WINDOW (modifier), _("Modifier"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (modifier), fixed6);

  modifier_titre_label = gtk_label_new (_("Modification Utilisateur"));
  gtk_widget_show (modifier_titre_label);
  gtk_fixed_put (GTK_FIXED (fixed6), modifier_titre_label, 96, 8);
  gtk_widget_set_size_request (modifier_titre_label, 200, 40);

  image35 = create_pixmap (modifier, "red.jpeg");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed6), image35, 0, 0);
  gtk_widget_set_size_request (image35, 312, 9);

  modifier_modifier_button = gtk_button_new ();
  gtk_widget_show (modifier_modifier_button);
  gtk_fixed_put (GTK_FIXED (fixed6), modifier_modifier_button, 120, 272);
  gtk_widget_set_size_request (modifier_modifier_button, 128, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (modifier_modifier_button), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  image34 = create_pixmap (modifier, "red.jpeg");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed6), image34, 80, 0);
  gtk_widget_set_size_request (image34, 312, 9);
  gtk_misc_set_alignment (GTK_MISC (image34), 0.44, 0.5);

  modif_date_checkbox = gtk_check_button_new_with_mnemonic (_("DATE DE NAISSANCE"));
  gtk_widget_show (modif_date_checkbox);
  gtk_fixed_put (GTK_FIXED (fixed6), modif_date_checkbox, 16, 152);
  gtk_widget_set_size_request (modif_date_checkbox, 192, 24);

  modif_sexe_checkbox = gtk_check_button_new_with_mnemonic (_("SEXE"));
  gtk_widget_show (modif_sexe_checkbox);
  gtk_fixed_put (GTK_FIXED (fixed6), modif_sexe_checkbox, 216, 152);
  gtk_widget_set_size_request (modif_sexe_checkbox, 118, 24);

  modif_nom_check = gtk_check_button_new_with_mnemonic (_("NOM"));
  gtk_widget_show (modif_nom_check);
  gtk_fixed_put (GTK_FIXED (fixed6), modif_nom_check, 16, 96);
  gtk_widget_set_size_request (modif_nom_check, 118, 24);

  modif_Prenom_checkbox = gtk_check_button_new_with_mnemonic (_("PRENOM"));
  gtk_widget_show (modif_Prenom_checkbox);
  gtk_fixed_put (GTK_FIXED (fixed6), modif_Prenom_checkbox, 216, 96);
  gtk_widget_set_size_request (modif_Prenom_checkbox, 118, 24);

  modif_etat_checkbox = gtk_check_button_new_with_mnemonic (_("STATUS"));
  gtk_widget_show (modif_etat_checkbox);
  gtk_fixed_put (GTK_FIXED (fixed6), modif_etat_checkbox, 128, 208);
  gtk_widget_set_size_request (modif_etat_checkbox, 118, 24);

  g_signal_connect ((gpointer) modifier_modifier_button, "clicked",
                    G_CALLBACK (on_modifier_modifier_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif_date_checkbox, "toggled",
                    G_CALLBACK (on_modif_date_checkbox_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_sexe_checkbox, "toggled",
                    G_CALLBACK (on_modif_sexe_checkbox_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_nom_check, "toggled",
                    G_CALLBACK (on_modif_nom_check_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_Prenom_checkbox, "toggled",
                    G_CALLBACK (on_modif_Prenom_checkbox_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_etat_checkbox, "toggled",
                    G_CALLBACK (on_modif_etat_checkbox_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (modifier, modifier_titre_label, "modifier_titre_label");
  GLADE_HOOKUP_OBJECT (modifier, image35, "image35");
  GLADE_HOOKUP_OBJECT (modifier, modifier_modifier_button, "modifier_modifier_button");
  GLADE_HOOKUP_OBJECT (modifier, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (modifier, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (modifier, image14, "image14");
  GLADE_HOOKUP_OBJECT (modifier, label41, "label41");
  GLADE_HOOKUP_OBJECT (modifier, image34, "image34");
  GLADE_HOOKUP_OBJECT (modifier, modif_date_checkbox, "modif_date_checkbox");
  GLADE_HOOKUP_OBJECT (modifier, modif_sexe_checkbox, "modif_sexe_checkbox");
  GLADE_HOOKUP_OBJECT (modifier, modif_nom_check, "modif_nom_check");
  GLADE_HOOKUP_OBJECT (modifier, modif_Prenom_checkbox, "modif_Prenom_checkbox");
  GLADE_HOOKUP_OBJECT (modifier, modif_etat_checkbox, "modif_etat_checkbox");

  return modifier;
}

GtkWidget*
create_confirmer_supp (void)
{
  GtkWidget *confirmer_supp;
  GtkWidget *fixed7;
  GtkWidget *button2;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label46;
  GtkWidget *label44;
  GtkWidget *supprimer_confirmer_button;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label45;

  confirmer_supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (confirmer_supp, 340, 245);
  gtk_window_set_title (GTK_WINDOW (confirmer_supp), _("Confirmer"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (confirmer_supp), fixed7);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed7), button2, 32, 176);
  gtk_widget_set_size_request (button2, 120, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button2), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox15), label46, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("Voulez Vous vraiment supprimer \ncet utilisateur ?"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed7), label44, 0, 72);
  gtk_widget_set_size_request (label44, 336, 56);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label44), 0.49, 0.55);

  supprimer_confirmer_button = gtk_button_new ();
  gtk_widget_show (supprimer_confirmer_button);
  gtk_fixed_put (GTK_FIXED (fixed7), supprimer_confirmer_button, 176, 176);
  gtk_widget_set_size_request (supprimer_confirmer_button, 120, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (supprimer_confirmer_button), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox14), label45, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_confirmer_annuler_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_confirmer_button, "clicked",
                    G_CALLBACK (on_confirmer_supp_supp_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmer_supp, confirmer_supp, "confirmer_supp");
  GLADE_HOOKUP_OBJECT (confirmer_supp, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (confirmer_supp, button2, "button2");
  GLADE_HOOKUP_OBJECT (confirmer_supp, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (confirmer_supp, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (confirmer_supp, image16, "image16");
  GLADE_HOOKUP_OBJECT (confirmer_supp, label46, "label46");
  GLADE_HOOKUP_OBJECT (confirmer_supp, label44, "label44");
  GLADE_HOOKUP_OBJECT (confirmer_supp, supprimer_confirmer_button, "supprimer_confirmer_button");
  GLADE_HOOKUP_OBJECT (confirmer_supp, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (confirmer_supp, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (confirmer_supp, image15, "image15");
  GLADE_HOOKUP_OBJECT (confirmer_supp, label45, "label45");

  return confirmer_supp;
}

GtkWidget*
create_confirmer_modifier (void)
{
  GtkWidget *confirmer_modifier;
  GtkWidget *fixed8;
  GtkWidget *button4;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label50;
  GtkWidget *label48;
  GtkWidget *button3;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label49;

  confirmer_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (confirmer_modifier, 340, 245);
  gtk_window_set_title (GTK_WINDOW (confirmer_modifier), _("Confirmer"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (confirmer_modifier), fixed8);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed8), button4, 32, 176);
  gtk_widget_set_size_request (button4, 120, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button4), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox17), label50, FALSE, FALSE, 0);

  label48 = gtk_label_new (_("Voulez vous vraiment modifier \ncet utilisateur ? "));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed8), label48, 16, 64);
  gtk_widget_set_size_request (label48, 320, 56);
  gtk_label_set_justify (GTK_LABEL (label48), GTK_JUSTIFY_CENTER);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed8), button3, 176, 176);
  gtk_widget_set_size_request (button3, 120, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button3), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox16), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_confirmer_annuler_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_confirmer_modifier_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmer_modifier, confirmer_modifier, "confirmer_modifier");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, button4, "button4");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, image18, "image18");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, label50, "label50");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, label48, "label48");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, button3, "button3");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, image17, "image17");
  GLADE_HOOKUP_OBJECT (confirmer_modifier, label49, "label49");

  return confirmer_modifier;
}

GtkWidget*
create_resultat_ajout_echec (void)
{
  GtkWidget *resultat_ajout_echec;
  GtkWidget *fixed9;
  GtkWidget *button5;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image19;
  GtkWidget *label51;
  GtkWidget *label52;

  resultat_ajout_echec = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (resultat_ajout_echec), fixed9);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed9), button5, 128, 152);
  gtk_widget_set_size_request (button5, 136, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button5), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image19 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox18), image19, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox18), label51, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("Echec de L'ajout de l'utilisateur"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed9), label52, 24, 16);
  gtk_widget_set_size_request (label52, 352, 88);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (resultat_ajout_echec, resultat_ajout_echec, "resultat_ajout_echec");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, button5, "button5");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, image19, "image19");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, label51, "label51");
  GLADE_HOOKUP_OBJECT (resultat_ajout_echec, label52, "label52");

  return resultat_ajout_echec;
}

GtkWidget*
create_resultat_modif_succ (void)
{
  GtkWidget *resultat_modif_succ;
  GtkWidget *fixed10;
  GtkWidget *button6;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label53;
  GtkWidget *label54;

  resultat_modif_succ = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (resultat_modif_succ), fixed10);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed10), button6, 128, 152);
  gtk_widget_set_size_request (button6, 136, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button6), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox19), label53, FALSE, FALSE, 0);

  label54 = gtk_label_new (_("Modification de l'utilisateur avec succ\303\251s"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed10), label54, 16, 24);
  gtk_widget_set_size_request (label54, 352, 88);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (resultat_modif_succ, resultat_modif_succ, "resultat_modif_succ");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, button6, "button6");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, image20, "image20");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, label53, "label53");
  GLADE_HOOKUP_OBJECT (resultat_modif_succ, label54, "label54");

  return resultat_modif_succ;
}

GtkWidget*
create_resultat_modif_echec (void)
{
  GtkWidget *resultat_modif_echec;
  GtkWidget *fixed11;
  GtkWidget *button7;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image21;
  GtkWidget *label55;
  GtkWidget *label56;

  resultat_modif_echec = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (resultat_modif_echec), fixed11);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed11), button7, 128, 152);
  gtk_widget_set_size_request (button7, 136, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button7), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image21 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox20), image21, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox20), label55, FALSE, FALSE, 0);

  label56 = gtk_label_new (_("Echec de la Modification "));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 24, 16);
  gtk_widget_set_size_request (label56, 352, 88);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (resultat_modif_echec, resultat_modif_echec, "resultat_modif_echec");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, button7, "button7");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, image21, "image21");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, label55, "label55");
  GLADE_HOOKUP_OBJECT (resultat_modif_echec, label56, "label56");

  return resultat_modif_echec;
}

GtkWidget*
create_resultat_supp_succ (void)
{
  GtkWidget *resultat_supp_succ;
  GtkWidget *fixed12;
  GtkWidget *button8;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image22;
  GtkWidget *label57;
  GtkWidget *label58;

  resultat_supp_succ = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (resultat_supp_succ), fixed12);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed12), button8, 128, 152);
  gtk_widget_set_size_request (button8, 136, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button8), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image22 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox21), image22, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox21), label57, FALSE, FALSE, 0);

  label58 = gtk_label_new (_("Supression de l'utilisateur avec Succ\303\251s "));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed12), label58, 24, 16);
  gtk_widget_set_size_request (label58, 352, 88);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (resultat_supp_succ, resultat_supp_succ, "resultat_supp_succ");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, button8, "button8");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, image22, "image22");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, label57, "label57");
  GLADE_HOOKUP_OBJECT (resultat_supp_succ, label58, "label58");

  return resultat_supp_succ;
}

GtkWidget*
create_resultat_supp_echec (void)
{
  GtkWidget *resultat_supp_echec;
  GtkWidget *fixed13;
  GtkWidget *button9;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label59;
  GtkWidget *label60;

  resultat_supp_echec = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (resultat_supp_echec), fixed13);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed13), button9, 128, 152);
  gtk_widget_set_size_request (button9, 136, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button9), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox22), label59, FALSE, FALSE, 0);

  label60 = gtk_label_new (_("Echec de la supression de l'Utilisateur"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed13), label60, 16, 32);
  gtk_widget_set_size_request (label60, 352, 88);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (resultat_supp_echec, resultat_supp_echec, "resultat_supp_echec");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, button9, "button9");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, image23, "image23");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, label59, "label59");
  GLADE_HOOKUP_OBJECT (resultat_supp_echec, label60, "label60");

  return resultat_supp_echec;
}

GtkWidget*
create_auth_echec (void)
{
  GtkWidget *auth_echec;
  GtkWidget *fixed14;
  GtkWidget *label62;
  GtkWidget *button10;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image24;
  GtkWidget *label61;

  auth_echec = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (auth_echec), fixed14);

  label62 = gtk_label_new (_("Veuillez verifiez vos identifiants"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed14), label62, 24, 16);
  gtk_widget_set_size_request (label62, 352, 88);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed14), button10, 123, 135);
  gtk_widget_set_size_request (button10, 136, 48);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button10), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image24 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox23), image24, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Continuer"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox23), label61, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_continuer_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (auth_echec, auth_echec, "auth_echec");
  GLADE_HOOKUP_OBJECT (auth_echec, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (auth_echec, label62, "label62");
  GLADE_HOOKUP_OBJECT (auth_echec, button10, "button10");
  GLADE_HOOKUP_OBJECT (auth_echec, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (auth_echec, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (auth_echec, image24, "image24");
  GLADE_HOOKUP_OBJECT (auth_echec, label61, "label61");

  return auth_echec;
}

GtkWidget*
create_modif_nom (void)
{
  GtkWidget *modif_nom;
  GtkWidget *fixed15;
  GtkWidget *nom_modif_entry;
  GtkWidget *label66;
  GtkWidget *label64;
  GtkWidget *valider_modif_nom;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image36;
  GtkWidget *label65;

  modif_nom = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modif_nom, 400, 250);
  gtk_window_set_title (GTK_WINDOW (modif_nom), _("Modifier"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (modif_nom), fixed15);

  nom_modif_entry = gtk_entry_new ();
  gtk_widget_show (nom_modif_entry);
  gtk_fixed_put (GTK_FIXED (fixed15), nom_modif_entry, 184, 80);
  gtk_widget_set_size_request (nom_modif_entry, 184, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_modif_entry), 8226);

  label66 = gtk_label_new (_("Nouveau Nom"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed15), label66, 56, 96);
  gtk_widget_set_size_request (label66, 112, 24);

  label64 = gtk_label_new (_("Modifier le Nom"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed15), label64, 96, 24);
  gtk_widget_set_size_request (label64, 224, 16);

  valider_modif_nom = gtk_button_new ();
  gtk_widget_show (valider_modif_nom);
  gtk_fixed_put (GTK_FIXED (fixed15), valider_modif_nom, 136, 176);
  gtk_widget_set_size_request (valider_modif_nom, 120, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (valider_modif_nom), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image36 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox24), image36, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox24), label65, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valider_modif_nom, "clicked",
                    G_CALLBACK (on_valider_modif_nom_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_nom, modif_nom, "modif_nom");
  GLADE_HOOKUP_OBJECT (modif_nom, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (modif_nom, nom_modif_entry, "nom_modif_entry");
  GLADE_HOOKUP_OBJECT (modif_nom, label66, "label66");
  GLADE_HOOKUP_OBJECT (modif_nom, label64, "label64");
  GLADE_HOOKUP_OBJECT (modif_nom, valider_modif_nom, "valider_modif_nom");
  GLADE_HOOKUP_OBJECT (modif_nom, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (modif_nom, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (modif_nom, image36, "image36");
  GLADE_HOOKUP_OBJECT (modif_nom, label65, "label65");

  return modif_nom;
}

GtkWidget*
create_modif_prenom (void)
{
  GtkWidget *modif_prenom;
  GtkWidget *fixed16;
  GtkWidget *entry_modif_prenom;
  GtkWidget *label68;
  GtkWidget *label67;
  GtkWidget *modif_prenom_button;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image37;
  GtkWidget *label69;

  modif_prenom = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modif_prenom, 400, 250);
  gtk_window_set_title (GTK_WINDOW (modif_prenom), _("Modifier"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (modif_prenom), fixed16);

  entry_modif_prenom = gtk_entry_new ();
  gtk_widget_show (entry_modif_prenom);
  gtk_fixed_put (GTK_FIXED (fixed16), entry_modif_prenom, 184, 80);
  gtk_widget_set_size_request (entry_modif_prenom, 184, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_prenom), 8226);

  label68 = gtk_label_new (_("Nouveau Prenom"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed16), label68, 56, 96);
  gtk_widget_set_size_request (label68, 112, 24);

  label67 = gtk_label_new (_("Modifier le Prenom"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed16), label67, 96, 24);
  gtk_widget_set_size_request (label67, 224, 16);

  modif_prenom_button = gtk_button_new ();
  gtk_widget_show (modif_prenom_button);
  gtk_fixed_put (GTK_FIXED (fixed16), modif_prenom_button, 136, 176);
  gtk_widget_set_size_request (modif_prenom_button, 120, 40);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (modif_prenom_button), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image37 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox25), image37, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox25), label69, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modif_prenom_button, "clicked",
                    G_CALLBACK (on_valider_modif_preno_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_prenom, modif_prenom, "modif_prenom");
  GLADE_HOOKUP_OBJECT (modif_prenom, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (modif_prenom, entry_modif_prenom, "entry_modif_prenom");
  GLADE_HOOKUP_OBJECT (modif_prenom, label68, "label68");
  GLADE_HOOKUP_OBJECT (modif_prenom, label67, "label67");
  GLADE_HOOKUP_OBJECT (modif_prenom, modif_prenom_button, "modif_prenom_button");
  GLADE_HOOKUP_OBJECT (modif_prenom, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (modif_prenom, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (modif_prenom, image37, "image37");
  GLADE_HOOKUP_OBJECT (modif_prenom, label69, "label69");

  return modif_prenom;
}

GtkWidget*
create_modif_age (void)
{
  GtkWidget *modif_age;
  GtkWidget *fixed17;
  GtkWidget *erreur_modif_age_label;
  GtkObject *modif_jour_spin_adj;
  GtkWidget *modif_jour_spin;
  GtkObject *modif_mois_spin_adj;
  GtkWidget *modif_mois_spin;
  GtkObject *modif_annee_spin_adj;
  GtkWidget *modif_annee_spin;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label73;
  GtkWidget *valider_modif_age_button;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image38;
  GtkWidget *label72;
  GtkWidget *label70;

  modif_age = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modif_age, 400, 250);
  gtk_window_set_title (GTK_WINDOW (modif_age), _("Modifier"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (modif_age), fixed17);

  erreur_modif_age_label = gtk_label_new ("");
  gtk_widget_show (erreur_modif_age_label);
  gtk_fixed_put (GTK_FIXED (fixed17), erreur_modif_age_label, 72, 144);
  gtk_widget_set_size_request (erreur_modif_age_label, 240, 32);

  modif_jour_spin_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  modif_jour_spin = gtk_spin_button_new (GTK_ADJUSTMENT (modif_jour_spin_adj), 1, 0);
  gtk_widget_show (modif_jour_spin);
  gtk_fixed_put (GTK_FIXED (fixed17), modif_jour_spin, 56, 104);
  gtk_widget_set_size_request (modif_jour_spin, 66, 35);

  modif_mois_spin_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  modif_mois_spin = gtk_spin_button_new (GTK_ADJUSTMENT (modif_mois_spin_adj), 1, 0);
  gtk_widget_show (modif_mois_spin);
  gtk_fixed_put (GTK_FIXED (fixed17), modif_mois_spin, 168, 104);
  gtk_widget_set_size_request (modif_mois_spin, 66, 35);

  modif_annee_spin_adj = gtk_adjustment_new (2020, 1910, 2022, 1, 10, 10);
  modif_annee_spin = gtk_spin_button_new (GTK_ADJUSTMENT (modif_annee_spin_adj), 1, 0);
  gtk_widget_show (modif_annee_spin);
  gtk_fixed_put (GTK_FIXED (fixed17), modif_annee_spin, 280, 104);
  gtk_widget_set_size_request (modif_annee_spin, 66, 35);

  label74 = gtk_label_new (_("MOIS"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed17), label74, 176, 80);
  gtk_widget_set_size_request (label74, 49, 17);

  label75 = gtk_label_new (_("ANNEE"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed17), label75, 280, 80);
  gtk_widget_set_size_request (label75, 64, 16);

  label73 = gtk_label_new (_("JOUR"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed17), label73, 48, 80);
  gtk_widget_set_size_request (label73, 64, 16);

  valider_modif_age_button = gtk_button_new ();
  gtk_widget_show (valider_modif_age_button);
  gtk_fixed_put (GTK_FIXED (fixed17), valider_modif_age_button, 136, 176);
  gtk_widget_set_size_request (valider_modif_age_button, 120, 40);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (valider_modif_age_button), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image38 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox26), image38, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox26), label72, FALSE, FALSE, 0);

  label70 = gtk_label_new (_("Modifier l'Age"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed17), label70, 96, 24);
  gtk_widget_set_size_request (label70, 224, 16);

  g_signal_connect ((gpointer) valider_modif_age_button, "clicked",
                    G_CALLBACK (on_valider_modif_age_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_age, modif_age, "modif_age");
  GLADE_HOOKUP_OBJECT (modif_age, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (modif_age, erreur_modif_age_label, "erreur_modif_age_label");
  GLADE_HOOKUP_OBJECT (modif_age, modif_jour_spin, "modif_jour_spin");
  GLADE_HOOKUP_OBJECT (modif_age, modif_mois_spin, "modif_mois_spin");
  GLADE_HOOKUP_OBJECT (modif_age, modif_annee_spin, "modif_annee_spin");
  GLADE_HOOKUP_OBJECT (modif_age, label74, "label74");
  GLADE_HOOKUP_OBJECT (modif_age, label75, "label75");
  GLADE_HOOKUP_OBJECT (modif_age, label73, "label73");
  GLADE_HOOKUP_OBJECT (modif_age, valider_modif_age_button, "valider_modif_age_button");
  GLADE_HOOKUP_OBJECT (modif_age, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (modif_age, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (modif_age, image38, "image38");
  GLADE_HOOKUP_OBJECT (modif_age, label72, "label72");
  GLADE_HOOKUP_OBJECT (modif_age, label70, "label70");

  return modif_age;
}

GtkWidget*
create_modif_sexe (void)
{
  GtkWidget *modif_sexe;
  GtkWidget *fixed18;
  GtkWidget *label78;
  GtkWidget *label76;
  GtkWidget *modif_sexe_femme;
  GSList *modif_sexe_femme_group = NULL;
  GtkWidget *modif_sexe_homme;
  GtkWidget *valider_modif_sexe;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image39;
  GtkWidget *label77;

  modif_sexe = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modif_sexe, 400, 250);
  gtk_window_set_title (GTK_WINDOW (modif_sexe), _("Modifier"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (modif_sexe), fixed18);

  label78 = gtk_label_new ("");
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed18), label78, 72, 144);
  gtk_widget_set_size_request (label78, 240, 32);

  label76 = gtk_label_new (_("Modifier le Sexe"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed18), label76, 88, 24);
  gtk_widget_set_size_request (label76, 224, 16);

  modif_sexe_femme = gtk_radio_button_new_with_mnemonic (NULL, _("FEMME"));
  gtk_widget_show (modif_sexe_femme);
  gtk_fixed_put (GTK_FIXED (fixed18), modif_sexe_femme, 240, 88);
  gtk_widget_set_size_request (modif_sexe_femme, 116, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modif_sexe_femme), modif_sexe_femme_group);
  modif_sexe_femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modif_sexe_femme));

  modif_sexe_homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (modif_sexe_homme);
  gtk_fixed_put (GTK_FIXED (fixed18), modif_sexe_homme, 48, 88);
  gtk_widget_set_size_request (modif_sexe_homme, 118, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modif_sexe_homme), modif_sexe_femme_group);
  modif_sexe_femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modif_sexe_homme));

  valider_modif_sexe = gtk_button_new ();
  gtk_widget_show (valider_modif_sexe);
  gtk_fixed_put (GTK_FIXED (fixed18), valider_modif_sexe, 136, 176);
  gtk_widget_set_size_request (valider_modif_sexe, 120, 40);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (valider_modif_sexe), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image39 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox27), image39, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox27), label77, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modif_sexe_femme, "toggled",
                    G_CALLBACK (on_modif_sexe_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_sexe_homme, "toggled",
                    G_CALLBACK (on_modif_sexe_homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) valider_modif_sexe, "clicked",
                    G_CALLBACK (on_valider_modif_sexe_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_sexe, modif_sexe, "modif_sexe");
  GLADE_HOOKUP_OBJECT (modif_sexe, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (modif_sexe, label78, "label78");
  GLADE_HOOKUP_OBJECT (modif_sexe, label76, "label76");
  GLADE_HOOKUP_OBJECT (modif_sexe, modif_sexe_femme, "modif_sexe_femme");
  GLADE_HOOKUP_OBJECT (modif_sexe, modif_sexe_homme, "modif_sexe_homme");
  GLADE_HOOKUP_OBJECT (modif_sexe, valider_modif_sexe, "valider_modif_sexe");
  GLADE_HOOKUP_OBJECT (modif_sexe, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (modif_sexe, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (modif_sexe, image39, "image39");
  GLADE_HOOKUP_OBJECT (modif_sexe, label77, "label77");

  return modif_sexe;
}

GtkWidget*
create_modif_etat (void)
{
  GtkWidget *modif_etat;
  GtkWidget *fixed19;
  GtkWidget *label86;
  GtkWidget *modif_etat_electeur;
  GSList *modif_etat_electeur_group = NULL;
  GtkWidget *modif_etat_agentbv;
  GtkWidget *modif_etat_valider;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image40;
  GtkWidget *label87;

  modif_etat = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modif_etat, 400, 250);
  gtk_window_set_title (GTK_WINDOW (modif_etat), _("Modifier"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (modif_etat), fixed19);

  label86 = gtk_label_new (_("Modifier le Status"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed19), label86, 88, 24);
  gtk_widget_set_size_request (label86, 224, 16);

  modif_etat_electeur = gtk_radio_button_new_with_mnemonic (NULL, _("Electeur"));
  gtk_widget_show (modif_etat_electeur);
  gtk_fixed_put (GTK_FIXED (fixed19), modif_etat_electeur, 48, 88);
  gtk_widget_set_size_request (modif_etat_electeur, 118, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modif_etat_electeur), modif_etat_electeur_group);
  modif_etat_electeur_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modif_etat_electeur));

  modif_etat_agentbv = gtk_radio_button_new_with_mnemonic (NULL, _("Agent De Bureau De Vote"));
  gtk_widget_show (modif_etat_agentbv);
  gtk_fixed_put (GTK_FIXED (fixed19), modif_etat_agentbv, 192, 88);
  gtk_widget_set_size_request (modif_etat_agentbv, 200, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modif_etat_agentbv), modif_etat_electeur_group);
  modif_etat_electeur_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modif_etat_agentbv));

  modif_etat_valider = gtk_button_new ();
  gtk_widget_show (modif_etat_valider);
  gtk_fixed_put (GTK_FIXED (fixed19), modif_etat_valider, 136, 176);
  gtk_widget_set_size_request (modif_etat_valider, 120, 40);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (modif_etat_valider), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image40 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox28), image40, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox28), label87, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modif_etat_electeur, "toggled",
                    G_CALLBACK (on_modif_etat_electeur_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_etat_agentbv, "toggled",
                    G_CALLBACK (on_modif_etat_agentbv_toggled),
                    NULL);
  g_signal_connect ((gpointer) modif_etat_valider, "clicked",
                    G_CALLBACK (on_modif_etat_valider_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modif_etat, modif_etat, "modif_etat");
  GLADE_HOOKUP_OBJECT (modif_etat, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (modif_etat, label86, "label86");
  GLADE_HOOKUP_OBJECT (modif_etat, modif_etat_electeur, "modif_etat_electeur");
  GLADE_HOOKUP_OBJECT (modif_etat, modif_etat_agentbv, "modif_etat_agentbv");
  GLADE_HOOKUP_OBJECT (modif_etat, modif_etat_valider, "modif_etat_valider");
  GLADE_HOOKUP_OBJECT (modif_etat, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (modif_etat, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (modif_etat, image40, "image40");
  GLADE_HOOKUP_OBJECT (modif_etat, label87, "label87");

  return modif_etat;
}

