/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Affichage;
  GtkWidget *authentification;
  GtkWidget *ajouter;
  GtkWidget *confirmer_ajout;
  GtkWidget *resultat_ajout_succ;
  GtkWidget *modifier;
  GtkWidget *confirmer_supp;
  GtkWidget *confirmer_modifier;
  GtkWidget *resultat_ajout_echec;
  GtkWidget *resultat_modif_succ;
  GtkWidget *resultat_modif_echec;
  GtkWidget *resultat_supp_succ;
  GtkWidget *resultat_supp_echec;
  GtkWidget *auth_echec;
  GtkWidget *modif_nom;
  GtkWidget *modif_prenom;
  GtkWidget *modif_age;
  GtkWidget *modif_sexe;
  GtkWidget *modif_etat;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*Affichage = create_Affichage ();
  gtk_widget_show (Affichage);*/
  authentification = create_authentification ();
  gtk_widget_show (authentification);
  /*ajouter = create_ajouter ();
  gtk_widget_show (ajouter);
  confirmer_ajout = create_confirmer_ajout ();
  gtk_widget_show (confirmer_ajout);
  resultat_ajout_succ = create_resultat_ajout_succ ();
  gtk_widget_show (resultat_ajout_succ);
  modifier = create_modifier ();
  gtk_widget_show (modifier);
  confirmer_supp = create_confirmer_supp ();
  gtk_widget_show (confirmer_supp);
  confirmer_modifier = create_confirmer_modifier ();
  gtk_widget_show (confirmer_modifier);
  resultat_ajout_echec = create_resultat_ajout_echec ();
  gtk_widget_show (resultat_ajout_echec);
  resultat_modif_succ = create_resultat_modif_succ ();
  gtk_widget_show (resultat_modif_succ);
  resultat_modif_echec = create_resultat_modif_echec ();
  gtk_widget_show (resultat_modif_echec);
  resultat_supp_succ = create_resultat_supp_succ ();
  gtk_widget_show (resultat_supp_succ);
  resultat_supp_echec = create_resultat_supp_echec ();
  gtk_widget_show (resultat_supp_echec);
  auth_echec = create_auth_echec ();
  gtk_widget_show (auth_echec);
  modif_nom = create_modif_nom ();
  gtk_widget_show (modif_nom);
  modif_prenom = create_modif_prenom ();
  gtk_widget_show (modif_prenom);
  modif_age = create_modif_age ();
  gtk_widget_show (modif_age);
  modif_sexe = create_modif_sexe ();
  gtk_widget_show (modif_sexe);
  modif_etat = create_modif_etat ();
  gtk_widget_show (modif_etat);*/

  gtk_main ();
  return 0;
}

